@web_api_HostAddress = http://localhost:5051

### Get all quotes (first page)
GET {{web_api_HostAddress}}/api/quotes?page=1&pageSize=10
Accept: application/json

### Get quote by ID (example: ID = 1)
GET {{web_api_HostAddress}}/api/quotes/1
Accept: application/json

### Get top 10 quotes by likes
GET {{web_api_HostAddress}}/api/quotes/top?count=10
Accept: application/json
