@web_api_HostAddress = http://localhost:5051

### Get all quotes
GET {{web_api_HostAddress}}/api/quotesapi?page=13&pageSize=-1
Accept: application/json

### Get quote by ID
GET {{web_api_HostAddress}}/api/quotesapi/1
Accept: application/json

### Get top 10 quotes by likes
GET {{web_api_HostAddress}}/api/quotesapi/top?count=10
Accept: application/json
